// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csenvujqyyubgxvfgknu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzZW52dWpxeXl1Ymd4dmZna251Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzODA2NDIsImV4cCI6MjA2MTk1NjY0Mn0.AeXYCIGLTRBD8gxii2P-bDXdTig2Kun7_06vTG4zAp4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);